### Tasks

* 1. Download a publicly available dataset of your choice (for example, a Flipkart product ratings dataset or Spotify song features) and split it into features (X) and target (y) for a regression problem.

In [68]:
import pandas as pd

In [69]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 2\Spotify.csv", encoding="latin1")

In [70]:
df.head()

,Column1,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,SeÃ±orit,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

In [71]:
X = df.select_dtypes(include=['number']).drop(columns=['Column1', 'Popularity'], errors='ignore')
y = df['Popularity']

In [72]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [73]:
X_scaled = scaler.fit_transform(X)
feature_names = X.columns

print("Features selected for the model:\n", list(feature_names))

Features selected for the model:
 ['Beats.Per.Minute', 'Energy', 'Danceability', 'Loudness..dB..', 'Liveness', 'Valence.', 'Length.', 'Acousticness..', 'Speechiness.']

* 2. Fit a Lasso regression model (L1 regularization) using scikit-learn's Lasso class on your dataset, and print out the coefficients for each feature.

In [74]:
from sklearn.linear_model import Lasso

In [75]:
lasso_model = Lasso(alpha=1.0, random_state=42)
lasso_model.fit(X_scaled, y)

Lasso(random_state=42)

In [76]:
print("Lasso Regression Coefficients:")
lasso_coeffs = pd.DataFrame({
    'Feature': feature_names,
    'Lasso Coefficient': lasso_model.coef_
})
lasso_coeffs

Lasso Regression Coefficients:

            Feature  Lasso Coefficient
0  Beats.Per.Minute           0.000000
1            Energy          -0.000000
2      Danceability          -0.000000
3    Loudness..dB..          -0.000000
4          Liveness           0.000000
5          Valence.          -0.410770
6           Length.          -0.000000
7    Acousticness..          -0.000000
8      Speechiness.           0.038819

* 3. Fit a Ridge regression model (L2 regularization) using scikit-learn's Ridge class on the same dataset, and compare the coefficients to those from the Lasso model.<br><br><em><strong>Hint:</strong> Look for features where Lasso sets coefficients exactly to zero but Ridge does not.</em>

In [77]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=5.0, random_state=42)
ridge_model.fit(X_scaled, y)

Ridge(alpha=5.0, random_state=42)

In [78]:
print("--- Comparison: Lasso vs. Ridge ---")
comparison_df = pd.DataFrame({
    'Feature': feature_names,
    'Lasso (L1)': lasso_model.coef_,
    'Ridge (L2)': ridge_model.coef_
})
print(comparison_df.to_string(index=False))

--- Comparison: Lasso vs. Ridge ---
         Feature  Lasso (L1)  Ridge (L2)
Beats.Per.Minute    0.000000    0.347895
          Energy   -0.000000    0.118747
    Danceability   -0.000000    0.094125
  Loudness..dB..   -0.000000    0.209213
        Liveness    0.000000    0.558408
        Valence.   -0.410770   -1.370482
         Length.   -0.000000   -0.514828
  Acousticness..   -0.000000   -0.177205
    Speechiness.    0.038819    0.878899

### Observation:"
Notice how Lasso sets features like Beats.Per.Minute, Energy and Danceability exactly to 0.0,
while Ridge shrinks them but keeps all of them non-zero.

* 4. Fit an ElasticNet regression model using scikit-learn's ElasticNet class, and observe how the coefficients differ from both Lasso and Ridge.<br><br><em><strong>Hint:</strong> Try changing the l1_ratio parameter and see how it affects the results.</em>

In [ ]:
from sklearn.linear_model import ElasticNet

# Fit ElasticNet with a balanced mix (l1_ratio = 0.5)
enet_balanced = ElasticNet(alpha=1.0, l1_ratio=0.5, random_state=42)
enet_balanced.fit(X_scaled, y)

ElasticNet(random_state=42)

In [ ]:
# Fit ElasticNet leaning more towards Ridge (l1_ratio = 0.2)
enet_ridge_heavy = ElasticNet(alpha=1.0, l1_ratio=0.2, random_state=42)
enet_ridge_heavy.fit(X_scaled, y)

ElasticNet(l1_ratio=0.2, random_state=42)

In [ ]:
print("ElasticNet Performance with different l1_ratios:")
enet_df = pd.DataFrame({
    'Feature': feature_names,
    'Lasso (alpha=1.0)': lasso_model.coef_,
    'ElasticNet (l1=0.5)': enet_balanced.coef_,
    'ElasticNet (l1=0.2)': enet_ridge_heavy.coef_,
    'Ridge (alpha=5.0)': ridge_model.coef_
})
enet_df

ElasticNet Performance with different l1_ratios:

,Feature,Lasso (alpha=1.0),ElasticNet (l1=0.5),ElasticNet (l1=0.2),Ridge (alpha=5.0)
0,Beats.Per.Minute,0.000000,0.130370,0.254679,0.347895
1,Energy,-0.000000,-0.000000,-0.000000,0.118747
2,Danceability,-0.000000,-0.000000,-0.000000,0.094125
3,Loudness..dB..,-0.000000,0.000000,0.000000,0.209213
4,Liveness,0.000000,0.000000,0.183163,0.558408
5,Valence.,-0.410770,-0.596754,-0.663247,-1.370482
6,Length.,-0.000000,-0.000000,-0.115901,-0.514828
7,Acousticness..,-0.000000,-0.000000,-0.000000,-0.177205
8,Speechiness.,0.038819,0.304196,0.395486,0.878899

* 5. Suppose you want to build a feature selector for a Zomato-style restaurant rating predictor. Use Lasso regression to select the most important features from your dataset, and list which features are kept (non-zero coefficients) and which are dropped.

In [ ]:
# Filter out features based on whether their Lasso coefficient is 0 or not
kept_features = feature_names[lasso_model.coef_ != 0].tolist()
dropped_features = feature_names[lasso_model.coef_ == 0].tolist()

print("Feature Selection Results using Lasso")
print(f"\n✅ Kept Features (Non-zero coefficients): {len(kept_features)}")
for col in kept_features:
    coef = lasso_model.coef_[feature_names.get_loc(col)]
    print(f"  - {col} (Weight: {coef:.4f})")

print(f"\n❌ Dropped Features (Coefficients forced to 0): {len(dropped_features)}")
for col in dropped_features:
    print(f"  - {col}")

Feature Selection Results using Lasso

✅ Kept Features (Non-zero coefficients): 2
  - Valence. (Weight: -0.4108)
  - Speechiness. (Weight: 0.0388)

❌ Dropped Features (Coefficients forced to 0): 7
  - Beats.Per.Minute
  - Energy
  - Danceability
  - Loudness..dB..
  - Liveness
  - Length.
  - Acousticness..

In [83]:
lasso_coeffs

            Feature  Lasso Coefficient
0  Beats.Per.Minute           0.000000
1            Energy          -0.000000
2      Danceability          -0.000000
3    Loudness..dB..          -0.000000
4          Liveness           0.000000
5          Valence.          -0.410770
6           Length.          -0.000000
7    Acousticness..          -0.000000
8      Speechiness.           0.038819