### Tasks

* 1. Download a small sample of IPL match data (CSV) with some missing values in player stats. Load it using pandas and print the number of missing values in each column.*

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assignment\Supervised\Session - 3\ipl_player_data.csv")

In [3]:
df.head()

      player_name  player_age team                   venue player_role
0     Virat Kohli        35.0  RCB  M. Chinnaswamy Stadium     Batsman
1        MS Dhoni        42.0  CSK  MA Chidambaram Stadium     Batsman
2    Rohit Sharma        36.0   MI        Wankhede Stadium     Batsman
3  Jasprit Bumrah         NaN   MI        Wankhede Stadium      Bowler
4        KL Rahul        31.0  LSG   Ekana Cricket Stadium     Batsman

In [4]:
df.isnull().sum()

player_name    0
player_age     3
team           2
venue          0
player_role    0
dtype: int64

* 2. For the 'player_age' column in your IPL dataset, fill all missing values with the median age using pandas' fillna() method and display the updated column.*

In [5]:
median_age = df['player_age'].median()

In [6]:
df['player_age'] = df['player_age'].fillna(median_age)

In [7]:
df['player_age'].isnull().sum()

np.int64(0)

In [8]:
print(df['player_age'])

0     35.0
1     42.0
2     36.0
3     33.0
4     31.0
5     30.0
6     33.0
7     35.0
8     38.0
9     29.0
10    33.0
11    33.0
12    33.0
13    33.0
14    29.0
Name: player_age, dtype: float64

* 3. Suppose the 'team' column in your IPL dataset contains missing values. Replace all missing team names with the constant value 'Unknown' and print the first 10 rows.*

In [9]:
df['team'] = df['team'].fillna('Unknown')

In [10]:
df['team'].head(10)

0        RCB
1        CSK
2         MI
3         MI
4        LSG
5         GT
6         DC
7        CSK
8       PBKS
9    Unknown
Name: team, dtype: str

* 4. Take the 'venue' column (categorical) from your IPL dataset and apply one-hot encoding using pandas' get_dummies(). Show the resulting DataFrame with the new columns.*

In [11]:
venue_encoded = pd.get_dummies(df['venue'])

In [12]:
venue_encoded.head()

,Arun Jaitley Stadium,Ekana Cricket Stadium,M. Chinnaswamy Stadium,MA Chidambaram Stadium,Narendra Modi Stadium,PCA Stadium,Rajiv Gandhi Stadium,Sawai Mansingh Stadium,Wankhede Stadium
0,False,False,True,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True
4,False,True,False,False,False,False,False,False,False

* 5. Use LabelEncoder from sklearn to encode the 'player_role' column (e.g., Batsman, Bowler, Allrounder) in your IPL dataset, and display the mapping from original roles to encoded values.*

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['player_role_encoded'] = le.fit_transform(df['player_role'])

In [ ]:
df

,player_name,player_age,team,venue,player_role,player_role_encoded
0,Virat Kohli,35.0,RCB,M. Chinnaswamy Stadium,Batsman,1
1,MS Dhoni,42.0,CSK,MA Chidambaram Stadium,Batsman,1
2,Rohit Sharma,36.0,MI,Wankhede Stadium,Batsman,1
3,Jasprit Bumrah,33.0,MI,Wankhede Stadium,Bowler,2
4,KL Rahul,31.0,LSG,Ekana Cricket Stadium,Batsman,1
5,Hardik Pandya,30.0,GT,Narendra Modi Stadium,Allrounder,0
6,Rishabh Pant,33.0,DC,Arun Jaitley Stadium,Batsman,1
7,Ravindra Jadeja,35.0,CSK,MA Chidambaram Stadium,Allrounder,0
8,Shikhar Dhawan,38.0,PBKS,PCA Stadium,Batsman,1
9,Shreyas Iyer,29.0,Unknown,Wankhede Stadium,Batsman,1
10,Suryakumar Yadav,33.0,MI,Wankhede Stadium,Batsman,1
11,Yuzvendra Chahal,33.0,RR,Sawai Mansingh Stadium,Bowler,2
12,Bhuvneshwar Kumar,33.0,SRH,Rajiv Gandhi Stadium,Bowler,2
13,Mohammed Shami,33.0,Unknown,Narendra Modi Stadium,Bowler,2
14,Sanju Samson,29.0,RR,Sawai Mansingh Stadium,Batsman,1